version: '2'

networks:
  basic:
    
services:

  zookeeper0.example.com:
    container_name: zookeeper0.example.com
    extends:
      file: ../base/docker-compose-base.yaml
      service: zookeeper0.example.com
    networks:
      - basic      

  zookeeper1.example.com:
    container_name: zookeeper1.example.com
    extends:
      file: ../base/docker-compose-base.yaml
      service: zookeeper1.example.com
    networks:
      - basic      

  zookeeper2.example.com:
    container_name: zookeeper2.example.com
    extends:
      file: ../base/docker-compose-base.yaml
      service: zookeeper2.example.com
    networks:
      - basic      

  kafka0.example.com:
    container_name: kafka0.example.com
    extends:
      file: ../base/docker-compose-base.yaml
      service: kafka0.example.com
    networks:
      - basic         
    depends_on:
      - zookeeper0.example.com
      - zookeeper1.example.com
      - zookeeper2.example.com

  kafka1.example.com:
    container_name: kafka1.example.com
    extends:
      file: ../base/docker-compose-base.yaml
      service: kafka1.example.com
    networks:
      - basic         
    depends_on:
      - zookeeper0.example.com
      - zookeeper1.example.com
      - zookeeper2.example.com

  kafka2.example.com:
    container_name: kafka2.example.com
    extends:
      file: ../base/docker-compose-base.yaml
      service: kafka2.example.com
    networks:
      - basic         
    depends_on:
      - zookeeper0.example.com
      - zookeeper1.example.com
      - zookeeper2.example.com

  kafka3.example.com:
    container_name: kafka3.example.com
    extends:
      file: ../base/docker-compose-base.yaml
      service: kafka3.example.com
    networks:
      - basic         
    depends_on:
      - zookeeper0.example.com
      - zookeeper1.example.com
      - zookeeper2.example.com